<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Department', 'doctrine');

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $department_id
 * @property string $name
 * @property Doctrine_Collection $Systemuser
 * 
 * @method integer             getDepartmentId()  Returns the current record's "department_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getSystemuser()    Returns the current record's "Systemuser" collection
 * @method Department          setDepartmentId()  Sets the current record's "department_id" value
 * @method Department          setName()          Sets the current record's "name" value
 * @method Department          setSystemuser()    Sets the current record's "Systemuser" collection
 * 
 * @package    space
 * @subpackage model
 * @author     Javkhlan Gansukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('department_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Systemuser', array(
             'local' => 'department_id',
             'foreign' => 'department_id'));
    }
}