<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menu', 'doctrine');

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_id
 * @property string $menu_name
 * @property string $menu_eng
 * @property integer $menu_parent
 * @property integer $menu_ord
 * @property string $menu_desc
 * @property string $menu_state
 * @property Menu $Parent
 * @property Doctrine_Collection $Roles
 * @property Doctrine_Collection $Children
 * 
 * @method integer             getMenuId()      Returns the current record's "menu_id" value
 * @method string              getMenuName()    Returns the current record's "menu_name" value
 * @method string              getMenuEng()     Returns the current record's "menu_eng" value
 * @method integer             getMenuParent()  Returns the current record's "menu_parent" value
 * @method integer             getMenuOrd()     Returns the current record's "menu_ord" value
 * @method string              getMenuDesc()    Returns the current record's "menu_desc" value
 * @method string              getMenuState()   Returns the current record's "menu_state" value
 * @method Menu                getParent()      Returns the current record's "Parent" value
 * @method Doctrine_Collection getRoles()       Returns the current record's "Roles" collection
 * @method Doctrine_Collection getChildren()    Returns the current record's "Children" collection
 * @method Menu                setMenuId()      Sets the current record's "menu_id" value
 * @method Menu                setMenuName()    Sets the current record's "menu_name" value
 * @method Menu                setMenuEng()     Sets the current record's "menu_eng" value
 * @method Menu                setMenuParent()  Sets the current record's "menu_parent" value
 * @method Menu                setMenuOrd()     Sets the current record's "menu_ord" value
 * @method Menu                setMenuDesc()    Sets the current record's "menu_desc" value
 * @method Menu                setMenuState()   Sets the current record's "menu_state" value
 * @method Menu                setParent()      Sets the current record's "Parent" value
 * @method Menu                setRoles()       Sets the current record's "Roles" collection
 * @method Menu                setChildren()    Sets the current record's "Children" collection
 * 
 * @package    space
 * @subpackage model
 * @author     Javkhlan Gansukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('menu_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('menu_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('menu_eng', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('menu_parent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('menu_ord', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('menu_desc', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('menu_state', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu as Parent', array(
             'local' => 'menu_parent',
             'foreign' => 'menu_id'));

        $this->hasMany('Roles', array(
             'refClass' => 'LinkingRoleMenu',
             'local' => 'menu_id',
             'foreign' => 'role_id'));

        $this->hasMany('Menu as Children', array(
             'local' => 'menu_id',
             'foreign' => 'menu_parent'));
    }
}