<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Linkingrolemenu', 'doctrine');

/**
 * BaseLinkingrolemenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $role_id
 * @property integer $menu_id
 * 
 * @method integer         getId()      Returns the current record's "id" value
 * @method integer         getRoleId()  Returns the current record's "role_id" value
 * @method integer         getMenuId()  Returns the current record's "menu_id" value
 * @method Linkingrolemenu setId()      Sets the current record's "id" value
 * @method Linkingrolemenu setRoleId()  Sets the current record's "role_id" value
 * @method Linkingrolemenu setMenuId()  Sets the current record's "menu_id" value
 * 
 * @package    space
 * @subpackage model
 * @author     Javkhlan Gansukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinkingrolemenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linkingrolemenu');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('role_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('menu_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}