task:
  class: sfDoctrineRouteCollection
  options:
    model:                Task
    module:               task
    prefix_path:          /task
    column:               task_id
    with_wildcard_routes: true

orders:
  class: sfDoctrineRouteCollection
  options:
    model:                Orders
    module:               orders
    prefix_path:          /orders
    column:               order_id
    with_wildcard_routes: true

roles:
  class: sfDoctrineRouteCollection
  options:
    model:                roles
    module:               roles
    prefix_path:          /roles
    column:               role_id
    with_wildcard_routes: true

menu:
  class: sfDoctrineRouteCollection
  options:
    model:                Menu
    module:               menu
    prefix_path:          /menu
    column:               menu_id
    with_wildcard_routes: true
systemuser:
  class: sfDoctrineRouteCollection
  options:
    model:                systemuser
    module:               systemuser
    prefix_path:          /systemuser
    column:               system_user_id
    with_wildcard_routes: true



# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /home
  param: { module: home, action: index }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /
  param: { module: home, action: index }
default:
  url:   /:module/:action/*

