<?php

/**
 * LinkingRoleMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkingRoleMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkingRoleMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkingRoleMenu');
    }
}