<?php

/**
 * SystemUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    space
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SystemUser extends BaseSystemUser
{
    public function __toString() {
        return $this->getDisplayName();
    }


    public function save(Doctrine_Connection $conn = null)
    {
        if(strlen($this->getLoginPassword())!=32){
            $this->setLoginPassword(md5($this->getLoginPassword()));
        }

        return parent::save($conn);
    }
   

}