<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/03/11 17:23:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bims',
  'enconding' => 'utf8',
  'persistent' => true,
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_general_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
