<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/03/11 17:14:22
sfConfig::add(array(
  'app_sf_twitter_bootstrap_web_dir' => '/sfTwitterBootstrapPlugin',
  'app_sf_twitter_bootstrap_image_dir' => '/sfTwitterBootstrapPlugin/images/',
  'app_sf_twitter_bootstrap_default_image' => 'gears.png',
  'app_sf_twitter_bootstrap_dashboard_url' => '@homepage',
  'app_sf_twitter_bootstrap_resize_mode' => 'thumbnail',
  'app_sf_twitter_bootstrap_site' => 'SPACE',
  'app_sf_twitter_bootstrap_include_path' => true,
  'app_sf_twitter_bootstrap_include_assets' => true,
  'app_sf_twitter_bootstrap_include_jquery' => true,
  'app_sf_twitter_bootstrap_include_jquery_no_conflict' => false,
  'app_sf_twitter_bootstrap_login_route' => '@sf_guard_signin',
  'app_sf_twitter_bootstrap_logout' => true,
  'app_sf_twitter_bootstrap_logout_route' => '@sf_guard_signout',
  'app_sf_twitter_bootstrap_top_link_to_fieldset' => true,
  'app_sf_twitter_bootstrap_display_top_pagination' => false,
  'app_sf_twitter_bootstrap_use_icons_in_button' => true,
  'app_sf_twitter_bootstrap_breadcrumb_root_name' => 'Home',
));
