Department:
  connection: doctrine
  tableName: department
  columns:
    department_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Systemuser:
      local: department_id
      foreign: department_id
      type: many
House:
  connection: doctrine
  tableName: house
  columns:
    house_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    level:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    parent_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Task:
      local: house_id
      foreign: house_id
      type: many
InvType:
  connection: doctrine
  tableName: inv_type
  columns:
    inv_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    parent_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    measure_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Measure:
      local: measure_id
      foreign: measure_id
      type: one
    Inventory:
      local: inv_type_id
      foreign: inv_type_id
      type: many
    InventoryBalance:
      local: inv_type_id
      foreign: inv_type_id
      type: many
    OrderDetail:
      local: inv_type_id
      foreign: inv_type_id
      type: many
Inventory:
  connection: doctrine
  tableName: inventory
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    inv_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    location_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sender_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    count:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    price:
      type: decimal(10,2)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    income:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    outcome:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Location:
      local: location_id
      foreign: location_id
      type: one
    InvType:
      local: inv_type_id
      foreign: inv_type_id
      type: one
InventoryBalance:
  connection: doctrine
  tableName: inventory_balance
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    balance:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    inv_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    location_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Location:
      local: location_id
      foreign: location_id
      type: one
    InvType:
      local: inv_type_id
      foreign: inv_type_id
      type: one
Linkingrolemenu:
  connection: doctrine
  tableName: linkingrolemenu
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    role_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    menu_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
Location:
  connection: doctrine
  tableName: location
  columns:
    location_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    parent_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Inventory:
      local: location_id
      foreign: location_id
      type: many
    InventoryBalance:
      local: location_id
      foreign: location_id
      type: many
Measure:
  connection: doctrine
  tableName: measure
  columns:
    measure_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    title:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    InvType:
      local: measure_id
      foreign: measure_id
      type: many
    Task:
      local: measure_id
      foreign: measure_id
      type: many
Menu:
  connection: doctrine
  tableName: menu
  columns:
    menu_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    menu_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu_eng:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu_parent:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu_ord:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu_desc:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu_state:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Parent: {foreignAlias: Children, foreign: menu_id, class: Menu, local: menu_parent}      
    Roles:
      class: Roles
      refClass: LinkingRoleMenu
      local: menu_id
      foreign: role_id
      
OrderDetail:
  connection: doctrine
  tableName: order_detail
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    order_count:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    confirm_count:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    issue_count:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    order_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    inv_type_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Orders:
      local: order_id
      foreign: order_id
      type: one
    InvType:
      local: inv_type_id
      foreign: inv_type_id
      type: one
Orders:
  connection: doctrine
  tableName: orders
  columns:
    order_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    system_user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    estimator:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    director:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    treasurer:
      type: string(20)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    order_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estimated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    confirm_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    issue_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    task_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Task:
      local: task_id
      foreign: task_id
      type: one
    Systemuser:
      local: system_user_id
      foreign: system_user_id
      type: one
    OrderDetail:
      local: order_id
      foreign: order_id
      type: many
Roles:
  connection: doctrine
  tableName: roles
  columns:
    role_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Systemuser:
      local: role_id
      foreign: role_id
      type: many
    Menu:
      class: Menu
      refClass: LinkingRoleMenu
      local: role_id
      foreign: menu_id
Systemuser:
  connection: doctrine
  tableName: systemuser
  columns:
    system_user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    login_name:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    login_password:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    display_name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    department_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    role_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Department:
      local: department_id
      foreign: department_id
      type: one
    Roles:
      local: role_id
      foreign: role_id
      type: one
    Orders:
      local: system_user_id
      foreign: system_user_id
      type: many
Task:
  connection: doctrine
  tableName: task
  columns:
    task_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    measure_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    house_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    exec_size:
      type: decimal(10,2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    unit_wage:
      type: decimal(10,2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    total_wage:
      type: decimal(10,2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Measure:
      local: measure_id
      foreign: measure_id
      type: one
    House:
      local: house_id
      foreign: house_id
      type: one
    Orders:
      local: task_id
      foreign: task_id
      type: many
